return {
    require("peanut.groups.neovim"),
    require("peanut.groups.dapui"),
    require("peanut.groups.git"),
    require("peanut.groups.lazy"),
    require("peanut.groups.lsp"),
    require("peanut.groups.markview"),
    require("peanut.groups.mason"),
    require("peanut.groups.neotest"),
    require("peanut.groups.snacks"),
    require("peanut.groups.statusline"),
    require("peanut.groups.telescope"),
    require("peanut.groups.treesitter"),
    require("peanut.groups.whichkey"),
    require("peanut.groups.miniicons"),
}
